version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-babel"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-base"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-browser"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-extension"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-node"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-react"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-test"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-vue"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config-webpack"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
    open-pull-requests-limit: 3
    versioning-strategy: "increase"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore:"
