name: Release
on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ">=20"
          check-latest: true
          cache: 'npm'
      - run: npm i -g npm@latest
      - run: npm ci --no-audit
      - run: npm t
  npm-publish:
    needs: test
    runs-on: ubuntu-latest
    name: Publish ${{ matrix.package }}
    permissions:
      id-token: write
    environment:
      name: production
      url: https://www.npmjs.com/package/@freaktechnik/${{ matrix.package }}
    strategy:
      matrix:
        package:
          - eslint-config-base
          - eslint-config-node
          - eslint-config-browser
          - eslint-config-babel
          - eslint-config-extension
          - eslint-config-react
          - eslint-config-test
          - eslint-config-vue
          - eslint-config-webpack
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ">=20"
          check-latest: true
          cache: 'npm'
      - run: npm i -g npm@latest
      #TODO make all the config dependencies also want this version in the package.json
      - run: npm publish --workspace @freaktechnik/${{matrix.package}}
