name: test
on: [push, pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ">=15.8"
          check-latest: true
          cache: 'npm'
      - run: npm i -g npm@latest
      - run: npm ci --ignore-scripts --no-audit
  lint-js:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ">=15.8"
          check-latest: true
          cache: 'npm'
      - run: npm i -g npm@latest
      - run: npm ci --no-audit
      - run: npm run lint
